import XCTest
import SwiftData
@testable import MyStoryDailyJournal

final class DigestEngineTests: XCTestCase {
    private func makeContext() -> ModelContext {
        ModelContext(PersistenceController.makeContainer(inMemory: true))
    }

    /// Regression test: an earlier version of `generateDigestIfNeeded`
    /// deleted every non-visit signal on each run, which would have wiped
    /// out shared items and watched-folder files pushed in independently.
    func testRegenerationPreservesPushedSignalKinds() async throws {
        let context = makeContext()
        let date = Date()

        SharedItemIngestor.ingest(title: "A note", text: "From Notes.", sourceApp: "Notes", on: date, in: context)

        let record = DayRecordRepository.record(for: date, in: context)
        let fileSignal = DaySignal(kind: .fileWatch, timestamp: date)
        fileSignal.setPayload(FileWatchPayload(fileName: "a.txt", folderName: "Journal"))
        fileSignal.dayRecord = record
        context.insert(fileSignal)
        try context.save()

        _ = await DigestEngine.generateDigestIfNeeded(for: date, in: context)
        _ = await DigestEngine.generateDigestIfNeeded(for: date, in: context)

        let kinds = Set(record.signals?.map(\.kind) ?? [])
        XCTAssertTrue(kinds.contains(.sharedItem))
        XCTAssertTrue(kinds.contains(.fileWatch))
    }

    func testGenerateDigestNeverOverwritesUserWrittenDay() async {
        let context = makeContext()
        let date = Date()

        DayRecordRepository.appendQuickReply("My own words.", on: date, in: context)
        let record = await DigestEngine.generateDigestIfNeeded(for: date, in: context)

        XCTAssertEqual(record.bodyText, "My own words.")
        XCTAssertEqual(record.source, .userWritten)
    }

    /// Regression test for the critical bug the audit caught:
    /// `DayRecordRepository.record(for:)` used to default new records to
    /// `.userWritten`, which made `DigestEngine`'s
    /// `guard !record.isUserWritten` bail out immediately for any day with
    /// no prior record — the composer never ran, and the day was left as a
    /// permanently blank "written" record. A brand-new day must actually
    /// get composed and marked `.autoGenerated`.
    func testGenerateDigestActuallyComposesABrandNewDay() async {
        let context = makeContext()
        let date = Date()

        let record = await DigestEngine.generateDigestIfNeeded(for: date, in: context)

        XCTAssertEqual(record.source, .autoGenerated)
        XCTAssertFalse(record.bodyText.isEmpty, "A freshly generated digest must never be blank text.")
    }

    func testRecordForNewDayStartsBlankNotUserWritten() {
        let context = makeContext()
        let record = DayRecordRepository.record(for: Date(), in: context)
        XCTAssertEqual(record.source, .blank)
        XCTAssertFalse(record.isUserWritten)
    }

    func testGenerateDigestIsIdempotent() async {
        let context = makeContext()
        let date = Date()

        _ = await DigestEngine.generateDigestIfNeeded(for: date, in: context)
        _ = await DigestEngine.generateDigestIfNeeded(for: date, in: context)

        let descriptor = FetchDescriptor<DayRecord>()
        let allRecords = (try? context.fetch(descriptor)) ?? []
        XCTAssertEqual(allRecords.count, 1)
    }

    /// Regression test: on a brand-new install (`lastDigestCheckDate` is
    /// `nil`), catch-up must not back-fill any days — there's nothing the
    /// app could have observed about a day before it was ever launched. An
    /// earlier version of this fallback backdated one extra day and
    /// fabricated a digest for the day before first launch.
    @MainActor
    func testCatchUpOnFirstRunGeneratesNoDays() async {
        let context = makeContext()
        SettingsStore.shared.lastDigestCheckDate = nil

        await DigestEngine.catchUpMissingDays(in: context)

        let descriptor = FetchDescriptor<DayRecord>()
        let allRecords = (try? context.fetch(descriptor)) ?? []
        XCTAssertTrue(allRecords.isEmpty, "First-ever run must not fabricate a digest for a day before install.")
    }
}
