import XCTest
import SwiftData
@testable import MyStoryDailyJournal

final class ProfileTests: XCTestCase {
    private var defaults: UserDefaults!
    private var suiteName: String!

    override func setUp() {
        super.setUp()
        suiteName = "ProfileTests.\(UUID().uuidString)"
        defaults = UserDefaults(suiteName: suiteName)
        defaults.removePersistentDomain(forName: suiteName)
    }

    override func tearDown() {
        defaults.removePersistentDomain(forName: suiteName)
        super.tearDown()
    }

    private func makeContext() -> ModelContext {
        ModelContext(PersistenceController.makeContainer(inMemory: true))
    }

    private var calendar: Calendar { Calendar(identifier: .gregorian) }

    /// A day `weeksAgo` back, on a specific weekday, at a specific hour.
    private func date(weeksAgo: Int, weekday: Int = 3, hour: Int = 20) -> Date {
        var components = DateComponents()
        components.year = 2026
        components.month = 6
        components.day = 3
        components.hour = hour
        let anchor = calendar.date(from: components)!
        let onWeekday = calendar.nextDate(
            after: anchor,
            matching: DateComponents(hour: hour, weekday: weekday),
            matchingPolicy: .nextTime,
            direction: .backward
        ) ?? anchor
        return calendar.date(byAdding: .day, value: -7 * weeksAgo, to: onWeekday)!
    }

    @discardableResult
    private func makeDay(
        _ date: Date,
        body: String = "",
        people: [String] = [],
        tags: [String] = [],
        visit: (name: String, kind: PlaceKind?)? = nil,
        workout: Bool = false,
        in context: ModelContext
    ) -> DayRecord {
        let record = DayRecord(date: date, source: body.isEmpty ? .autoGenerated : .userWritten, bodyText: body)
        record.editedAt = date
        context.insert(record)

        record.people = people.map { name in
            let person = Person(name: name)
            context.insert(person)
            return person
        }
        record.tags = tags.map { name in
            let tag = Tag(name: name)
            context.insert(tag)
            return tag
        }

        var signals: [DaySignal] = []
        if let visit {
            let signal = DaySignal(kind: .visit, timestamp: date)
            signal.setPayload(VisitPayload(
                placeName: visit.name,
                latitude: 0,
                longitude: 0,
                isFullAccuracy: true,
                placeKindRaw: visit.kind?.rawValue
            ))
            signals.append(signal)
        }
        if workout {
            let signal = DaySignal(kind: .activity, timestamp: date)
            signal.setPayload(ActivityPayload(
                stepCount: 8000,
                distanceMeters: 5000,
                workoutSummaries: ["a 5 km run"]
            ))
            signals.append(signal)
        }
        for signal in signals {
            signal.dayRecord = record
            context.insert(signal)
        }
        record.signals = signals
        try? context.save()
        return record
    }

    // MARK: - Learning

    func testLearnsWhoRecursAndWhereTheyTurnUp() {
        let context = makeContext()
        for week in 0..<5 {
            makeDay(
                date(weeksAgo: week),
                people: ["Dana"],
                visit: (name: "the gym", kind: .gym),
                in: context
            )
        }

        ProfileLearner.learn(in: context, now: date(weeksAgo: 0), defaults: defaults)

        let facts = (try? context.fetch(FetchDescriptor<ProfileFact>())) ?? []
        let dana = facts.first { $0.kind == .person && $0.subject == "Dana" }
        XCTAssertNotNil(dana, "Someone tagged on five days is part of this life.")
        XCTAssertEqual(dana?.observationCount, 5)
        XCTAssertTrue(dana?.detail.contains("the gym") == true, "Got: \(dana?.detail ?? "")")
    }

    func testDoesNotInventAHabitFromOneOrTwoDays() {
        let context = makeContext()
        makeDay(date(weeksAgo: 0), people: ["Sam"], in: context)
        makeDay(date(weeksAgo: 1), people: ["Sam"], in: context)

        ProfileLearner.learn(in: context, now: date(weeksAgo: 0), defaults: defaults)

        let facts = (try? context.fetch(FetchDescriptor<ProfileFact>())) ?? []
        XCTAssertFalse(facts.contains { $0.subject == "Sam" }, "Twice is a coincidence, not a pattern.")
    }

    func testLearnsAPlaceAndWhatTheWriterSaidItWas() {
        let context = makeContext()
        for week in 0..<4 {
            makeDay(date(weeksAgo: week), visit: (name: "home", kind: .home), in: context)
        }

        ProfileLearner.learn(in: context, now: date(weeksAgo: 0), defaults: defaults)

        let facts = (try? context.fetch(FetchDescriptor<ProfileFact>())) ?? []
        let place = facts.first { $0.kind == .place && $0.subject == "home" }
        XCTAssertNotNil(place)
        XCTAssertEqual(place?.observationCount, 4)
    }

    func testLearnsTheWritersVoiceFromTheirOwnWordsOnly() {
        let context = makeContext()
        for week in 0..<4 {
            makeDay(date(weeksAgo: week), body: "Short one. Ran the loop. Slept fine.", in: context)
        }

        ProfileLearner.learn(in: context, now: date(weeksAgo: 0), defaults: defaults)

        let facts = (try? context.fetch(FetchDescriptor<ProfileFact>())) ?? []
        let voice = facts.filter { $0.kind == .voice }
        XCTAssertTrue(voice.contains { $0.subject == "entry length" })
        XCTAssertTrue(
            voice.contains { $0.subject == "sentences" && $0.detail.contains("short") },
            "Three-word sentences are short ones."
        )
    }

    func testLearningIsIdempotentAndKeepsWhatTheWriterDecided() {
        let context = makeContext()
        for week in 0..<5 {
            makeDay(date(weeksAgo: week), people: ["Dana"], in: context)
        }
        let now = date(weeksAgo: 0)

        ProfileLearner.learn(in: context, now: now, defaults: defaults)
        let dana = (try? context.fetch(FetchDescriptor<ProfileFact>()))?
            .first { $0.subject == "Dana" }
        dana?.isMuted = true
        try? context.save()

        ProfileLearner.learn(in: context, now: now, defaults: defaults)

        let facts = (try? context.fetch(FetchDescriptor<ProfileFact>())) ?? []
        let matching = facts.filter { $0.subject == "Dana" }
        XCTAssertEqual(matching.count, 1, "Re-learning must update a fact, not duplicate it.")
        XCTAssertEqual(matching.first?.isMuted, true, "A muted fact stays muted however often it's seen again.")
    }

    func testLearningStopsWhenTheWriterTurnsItOff() {
        let context = makeContext()
        for week in 0..<5 {
            makeDay(date(weeksAgo: week), people: ["Dana"], in: context)
        }
        defaults.set(false, forKey: ProfileLearner.learningEnabledKey)

        ProfileLearner.learn(in: context, now: date(weeksAgo: 0), defaults: defaults)

        XCTAssertTrue(((try? context.fetch(FetchDescriptor<ProfileFact>())) ?? []).isEmpty)
    }

    func testForgettingClearsTheConclusionsAndNotTheJournal() {
        let context = makeContext()
        for week in 0..<5 {
            makeDay(date(weeksAgo: week), people: ["Dana"], in: context)
        }
        ProfileLearner.learn(in: context, now: date(weeksAgo: 0), defaults: defaults)

        ProfileLearner.forgetEverything(in: context, defaults: defaults)

        XCTAssertTrue(((try? context.fetch(FetchDescriptor<ProfileFact>())) ?? []).isEmpty)
        XCTAssertEqual(((try? context.fetch(FetchDescriptor<DayRecord>())) ?? []).count, 5)
    }

    func testARepeatedPatternBecomesAWeekdayHabit() {
        let dates = (0..<5).map { date(weeksAgo: $0, weekday: 3) }
        XCTAssertEqual(
            ProfileLearner.weekdayPattern(of: dates, calendar: calendar),
            "mostly on Tuesdays"
        )
    }

    func testScatteredDaysAreNotAHabit() {
        let dates = (1...5).map { date(weeksAgo: 0, weekday: $0) }
        XCTAssertNil(ProfileLearner.weekdayPattern(of: dates, calendar: calendar))
    }

    func testDistinctiveWordsSkipTheOnesEveryDiaryUses() {
        let words = ProfileLearner.distinctiveWords(in: [
            "Bouldering again today, felt strong",
            "Bouldering after work, really good",
            "Bouldering with Dana, went well today",
        ])
        XCTAssertEqual(words.first, "bouldering")
        XCTAssertFalse(words.contains("today"))
        XCTAssertFalse(words.contains("felt"))
    }

    // MARK: - Choosing what to tell the writing

    private func makeFact(
        _ kind: ProfileFactKind,
        _ subject: String,
        detail: String? = nil,
        count: Int = 5,
        in context: ModelContext
    ) -> ProfileFact {
        let fact = ProfileFact(
            kind: kind,
            subject: subject,
            detail: detail ?? "\(subject) — seen \(count) times.",
            observationCount: count
        )
        context.insert(fact)
        return fact
    }

    func testTheBriefBringsThePeopleAndPlacesTodayIsAbout() {
        let context = makeContext()
        let dana = makeFact(.person, "Dana", in: context)
        let priya = makeFact(.person, "Priya", in: context)
        let gym = makeFact(.place, "the gym", in: context)

        let chosen = ProfileBrief.select(
            from: [dana, priya, gym],
            cues: ProfileBrief.Cues(people: ["Dana"], places: ["the gym"]),
            budget: 200
        )

        XCTAssertTrue(chosen.contains { $0.subject == "Dana" })
        XCTAssertTrue(chosen.contains { $0.subject == "the gym" })
        XCTAssertFalse(chosen.contains { $0.subject == "Priya" }, "Priya isn't part of this day.")
    }

    func testVoiceComesAlongWhateverTheDayWas() {
        let context = makeContext()
        let voice = makeFact(.voice, "entry length", detail: "Keeps entries short.", count: 1, in: context)
        let stranger = makeFact(.person, "Priya", count: 40, in: context)

        let chosen = ProfileBrief.select(from: [voice, stranger], cues: ProfileBrief.Cues(), budget: 60)
        XCTAssertEqual(chosen.first?.subject, "entry length")
    }

    func testAMutedFactIsNeverUsedAndAPinnedOneAlwaysIs() {
        let context = makeContext()
        let muted = makeFact(.person, "Dana", count: 40, in: context)
        muted.isMuted = true
        let pinned = makeFact(.theme, "climbing", count: 1, in: context)
        pinned.isPinned = true

        let chosen = ProfileBrief.select(
            from: [muted, pinned],
            cues: ProfileBrief.Cues(people: ["Dana"]),
            budget: 500
        )

        XCTAssertFalse(chosen.contains { $0.subject == "Dana" })
        XCTAssertTrue(chosen.contains { $0.subject == "climbing" })
    }

    func testTheBriefStaysInsideItsBudget() {
        let context = makeContext()
        let facts = (0..<40).map { makeFact(.theme, "theme\($0)", count: 40 - $0, in: context) }

        let chosen = ProfileBrief.select(from: facts, cues: ProfileBrief.Cues(), budget: 120)
        let spent = chosen.map(\.sentence.count).reduce(0, +)

        XCTAssertLessThanOrEqual(spent, 120)
        XCTAssertFalse(chosen.isEmpty)
    }

    func testTheRenderedBriefGroupsWhatItKnows() {
        let context = makeContext()
        let voice = makeFact(.voice, "entry length", detail: "Keeps entries short.", in: context)
        let dana = makeFact(.person, "Dana", detail: "Dana — appears on 42 days.", in: context)

        let rendered = ProfileBrief.render([voice, dana])
        XCTAssertTrue(rendered?.contains("Voice: Keeps entries short.") == true)
        XCTAssertTrue(rendered?.contains("People: Dana — appears on 42 days.") == true)
    }
}
