import XCTest
@testable import MyStoryDailyJournal

final class StreakCalculatorTests: XCTestCase {
    private func day(_ offset: Int, source: DayRecordSource, from today: Date) -> DayRecord {
        let date = Calendar.current.date(byAdding: .day, value: offset, to: DateUtilities.startOfDay(for: today))!
        return DayRecord(date: date, source: source)
    }

    func testStreakCountsAutoAndWrittenDaysButWrittenCountOnlyCountsUserWords() {
        let today = Date()
        let days = [
            day(0, source: .userWritten, from: today),
            day(-1, source: .autoGenerated, from: today),
            day(-2, source: .converted, from: today),
        ]

        let stats = StreakCalculator.stats(for: days, asOf: today)

        XCTAssertEqual(stats.currentStreak, 3)
        XCTAssertEqual(stats.writtenCount, 2, "Only userWritten/converted days count toward the written total.")
    }

    func testBlankDayBreaksTheStreak() {
        let today = Date()
        let days = [
            day(0, source: .userWritten, from: today),
            day(-1, source: .blank, from: today),
            day(-2, source: .userWritten, from: today),
        ]

        let stats = StreakCalculator.stats(for: days, asOf: today)

        XCTAssertEqual(stats.currentStreak, 1, "A blank day must stop the streak, even if older days are covered.")
        XCTAssertEqual(stats.writtenCount, 1)
    }

    func testNoRecordForTodayMeansZeroStreak() {
        let today = Date()
        let days = [day(-1, source: .userWritten, from: today)]

        let stats = StreakCalculator.stats(for: days, asOf: today)

        XCTAssertEqual(stats.currentStreak, 0)
        XCTAssertEqual(stats.writtenCount, 0)
    }
}
