import XCTest
import SwiftData
@testable import MyStoryDailyJournal

final class TagLoggerTests: XCTestCase {
    private func makeContext() -> ModelContext {
        ModelContext(PersistenceController.makeContainer(inMemory: true))
    }

    func testLogTagCreatesRecordWithTag() {
        let context = makeContext()
        let record = TagLogger.logTag(named: PresetTag.good.rawValue, on: Date(), in: context)

        XCTAssertEqual(record.tags?.map(\.name), ["Good"])
        XCTAssertEqual(record.source, .userWritten)
    }

    func testLogTagIsIdempotentPerDay() {
        let context = makeContext()
        let date = Date()
        _ = TagLogger.logTag(named: PresetTag.busy.rawValue, on: date, in: context)
        let record = TagLogger.logTag(named: PresetTag.busy.rawValue, on: date, in: context)

        XCTAssertEqual(record.tags?.count, 1, "Tapping the same tag twice must not duplicate it.")
    }

    func testLogTagOnAutoGeneratedDayConvertsSource() {
        let context = makeContext()
        let date = Date()
        let record = DayRecordRepository.record(for: date, in: context)
        record.source = .autoGenerated
        try? context.save()

        let updated = TagLogger.logTag(named: PresetTag.quiet.rawValue, on: date, in: context)
        XCTAssertEqual(updated.source, .converted)
    }
}
