import SwiftUI
import SwiftData

/// Reverse-chronological list, Notes-style: date, first line, a small dot
/// for written vs. auto-generated. No cards or shadows (§16).
struct DayListView: View {
    @Query(sort: \DayRecord.date, order: .reverse) private var days: [DayRecord]
    @Environment(\.modelContext) private var context

    var body: some View {
        List {
            ForEach(days) { day in
                NavigationLink(value: day.date) {
                    DayRow(day: day)
                }
                .swipeActions(edge: .trailing, allowsFullSwipe: false) {
                    Button(role: .destructive) {
                        context.delete(day)
                        try? context.save()
                    } label: {
                        Label("Delete", systemImage: "trash")
                    }

                    if day.source == .autoGenerated {
                        Button {
                            day.source = .converted
                        } label: {
                            Label("Convert", systemImage: "pencil")
                        }
                        .tint(.accentColor)
                    }
                }
            }
        }
        .listStyle(.plain)
        .overlay {
            if days.isEmpty {
                ContentUnavailableView(
                    "No days yet",
                    systemImage: "book",
                    description: Text("Write today's entry to start your journal.")
                )
            }
        }
    }
}

private struct DayRow: View {
    let day: DayRecord

    var body: some View {
        HStack(alignment: .top, spacing: 12) {
            Circle()
                .fill(day.isUserWritten ? Color.accentColor : Color.secondary.opacity(0.4))
                .frame(width: 8, height: 8)
                .padding(.top, 6)

            VStack(alignment: .leading, spacing: 2) {
                Text(day.date, style: .date)
                    .font(.subheadline.weight(.medium))
                Text(day.previewLine.isEmpty ? "No entry" : day.previewLine)
                    .font(.body)
                    .foregroundStyle(day.previewLine.isEmpty ? .tertiary : .secondary)
                    .lineLimit(1)
            }
        }
        .padding(.vertical, 4)
    }
}
