import SwiftUI
import SwiftData

/// Reverse-chronological list, Notes-style: date, first line, a small dot
/// for written vs. auto-generated. No cards or shadows (§16).
struct DayListView: View {
    @Query(sort: \DayRecord.date, order: .reverse) private var days: [DayRecord]
    @Environment(\.modelContext) private var context

    private var streakStats: StreakCalculator.Stats {
        StreakCalculator.stats(for: days)
    }

    var body: some View {
        List {
            if streakStats.currentStreak > 0 {
                Section {
                    StreakSummaryRow(stats: streakStats)
                }
            }

            ForEach(days) { day in
                NavigationLink(value: day.date) {
                    DayRow(day: day)
                }
                .swipeActions(edge: .trailing, allowsFullSwipe: false) {
                    Button(role: .destructive) {
                        context.delete(day)
                        try? context.save()
                    } label: {
                        Label("Delete", systemImage: "trash")
                    }

                    if day.source == .autoGenerated {
                        // Opens the entry for editing rather than silently
                        // flipping the source — a converted day should
                        // actually contain the user's own words (§10).
                        NavigationLink(value: day.date) {
                            Label("Convert", systemImage: "pencil")
                        }
                        .tint(.accentColor)
                    }
                }
            }
        }
        .listStyle(.plain)
        .overlay {
            if days.isEmpty {
                ContentUnavailableView(
                    "No days yet",
                    systemImage: "book",
                    description: Text("Write today's entry to start your journal.")
                )
            }
        }
    }
}

/// Purely informational — no fire emoji, no "don't break the chain" framing,
/// no red/warning color for a low written count. Auto days count toward the
/// streak exactly the same as written ones (§8).
private struct StreakSummaryRow: View {
    let stats: StreakCalculator.Stats

    var body: some View {
        HStack {
            Text("\(stats.currentStreak) day\(stats.currentStreak == 1 ? "" : "s") covered")
            Spacer()
            Text("\(stats.writtenCount) in your own words")
                .foregroundStyle(.secondary)
        }
        .font(.footnote)
    }
}

private struct DayRow: View {
    let day: DayRecord

    var body: some View {
        HStack(alignment: .top, spacing: 12) {
            Circle()
                .fill(day.isUserWritten ? Color.accentColor : Color.secondary.opacity(0.4))
                .frame(width: 8, height: 8)
                .padding(.top, 6)

            VStack(alignment: .leading, spacing: 2) {
                HStack(spacing: 6) {
                    Text(day.date, style: .date)
                        .font(.subheadline.weight(.medium))
                    if day.source == .autoGenerated {
                        Text("Auto")
                            .font(.caption2.weight(.medium))
                            .padding(.horizontal, 6)
                            .padding(.vertical, 1)
                            .background(Color.secondary.opacity(0.15))
                            .clipShape(Capsule())
                            .foregroundStyle(.secondary)
                    }
                }
                Text(day.previewLine.isEmpty ? "No entry" : day.previewLine)
                    .font(.body)
                    .foregroundStyle(day.previewLine.isEmpty ? .tertiary : .secondary)
                    .lineLimit(1)
            }
        }
        .padding(.vertical, 4)
    }
}
