import SwiftUI
import SwiftData

/// A plain text canvas. No character counter, no streak warning, no
/// placeholder copy — none of the pressure UI that belongs to reminder
/// logic instead (§6).
struct FreeformEntryView: View {
    @Bindable var record: DayRecord
    @Environment(\.modelContext) private var context

    var body: some View {
        TextEditor(text: $record.bodyText)
            .font(.system(.body, design: .serif))
            .scrollContentBackground(.hidden)
            .padding(.horizontal)
            .onChange(of: record.bodyText) { _, _ in
                record.editedAt = .now
                if record.source == .autoGenerated {
                    record.source = .converted
                }
            }
            .onDisappear {
                try? context.save()
                if !record.bodyText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                    NotificationManager.cancelPendingRemindersForToday()
                }
            }
    }
}
