import SwiftUI
import SwiftData

/// A plain text canvas. No character counter, no streak warning, no
/// placeholder copy — none of the pressure UI that belongs to reminder
/// logic instead (§6).
struct FreeformEntryView: View {
    @Bindable var record: DayRecord
    @Environment(\.modelContext) private var context

    var body: some View {
        TextEditor(text: $record.bodyText)
            .font(.system(.body, design: .serif))
            .scrollContentBackground(.hidden)
            .padding(.horizontal)
            .onChange(of: record.bodyText) { _, _ in
                record.editedAt = .now
                switch record.source {
                case .autoGenerated:
                    record.source = .converted
                case .blank:
                    record.source = .userWritten
                case .userWritten, .converted:
                    break
                }
            }
            .onDisappear {
                try? context.save()
                // The writer's own words are the best evidence there is
                // about how they write and who they mean; fold them in,
                // no more often than the learner's own interval allows.
                ProfileLearner.learnIfNeeded(in: context)
                if !record.bodyText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                    NotificationManager.cancelPendingRemindersForToday()
                }
                LiveActivityManager.refreshForToday(isJournaled: record.isUserWritten)
            }
    }
}
