import SwiftUI
import SwiftData

/// A short sequence of prompts, one at a time, composed into the entry body
/// only after the user reviews and can lightly edit the result. Never saves
/// silently (§6, acceptance criteria).
struct GuidedEntryView: View {
    @Bindable var record: DayRecord
    let questionSet: QuestionSet
    var onSave: () -> Void = {}

    @Environment(\.modelContext) private var context

    @State private var answers: [String]
    @State private var currentIndex = 0
    @State private var isReviewing = false
    @State private var composedText = ""

    init(record: DayRecord, questionSet: QuestionSet, onSave: @escaping () -> Void = {}) {
        self.record = record
        self.questionSet = questionSet
        self.onSave = onSave
        _answers = State(initialValue: Array(repeating: "", count: questionSet.prompts.count))
    }

    var body: some View {
        if isReviewing {
            reviewStep
        } else {
            promptStep
        }
    }

    private var promptStep: some View {
        VStack(alignment: .leading, spacing: 20) {
            Text("Question \(currentIndex + 1) of \(questionSet.prompts.count)")
                .font(.caption)
                .foregroundStyle(.secondary)

            Text(questionSet.prompts[currentIndex])
                .font(.title3)

            TextField("", text: $answers[currentIndex], axis: .vertical)
                .textFieldStyle(.roundedBorder)
                .lineLimit(3...6)

            Spacer()

            HStack {
                if currentIndex > 0 {
                    Button("Back") { currentIndex -= 1 }
                }
                Spacer()
                Button(currentIndex == questionSet.prompts.count - 1 ? "Continue" : "Next") {
                    advance()
                }
                .buttonStyle(.borderedProminent)
            }
        }
        .padding()
    }

    private var reviewStep: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Your entry")
                .font(.caption)
                .foregroundStyle(.secondary)

            TextEditor(text: $composedText)
                .font(.system(.body, design: .serif))
                .scrollContentBackground(.hidden)

            HStack {
                Button("Back to questions") { isReviewing = false }
                Spacer()
                Button("Save") { save() }
                    .buttonStyle(.borderedProminent)
            }
        }
        .padding()
    }

    private func advance() {
        if currentIndex < questionSet.prompts.count - 1 {
            currentIndex += 1
        } else {
            composedText = Self.compose(answers: answers)
            isReviewing = true
        }
    }

    private func save() {
        record.bodyText = composedText
        record.source = record.source == .autoGenerated ? .converted : .userWritten
        record.editedAt = .now
        try? context.save()
        LiveActivityManager.refreshForToday(isJournaled: record.isUserWritten)
        onSave()
    }

    /// Joins non-empty answers into short paragraphs — the same lightweight
    /// template-composition approach the digest uses (§9).
    static func compose(answers: [String]) -> String {
        answers
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }
            .joined(separator: "\n\n")
    }
}
