import Foundation
import SwiftData

/// Source of a day's record. Auto-generated days can later be edited into
/// `converted` once the user turns a digest into their own words.
///
/// `blank` is the state a record is born in — created (by
/// `DayRecordRepository`, a live signal push, etc.) but not yet actually
/// written, tagged, or digested. It exists specifically so a freshly
/// created record is never mistaken for `userWritten`: `DigestEngine`
/// skips generating a digest for any day whose source already counts as
/// user-written, so if creation defaulted to `userWritten` (as it once
/// did), simply opening an empty day — or a background signal touching it
/// first — would permanently mark that day as "written" with nothing in
/// it, and it could never become a digest. `blank` closes that hole.
enum DayRecordSource: String, Codable, Sendable {
    case blank
    case userWritten
    case autoGenerated
    case converted
}

/// One calendar day in the user's journal. A day is bounded by local midnight
/// in the timezone it occurred in, so `timeZoneIdentifier` travels with the
/// record rather than being derived from the device's current timezone.
///
/// Every field has a default or is optional to satisfy SwiftData's CloudKit
/// schema requirements (see build spec §11) even though CloudKit sync itself
/// lands in a later milestone.
@Model
final class DayRecord {
    /// Not a schema-level unique constraint — SwiftData/CloudKit doesn't
    /// support those (build spec §11). Uniqueness per calendar day is
    /// enforced in application logic by `DayRecordRepository`.
    var date: Date

    var sourceRaw: String = DayRecordSource.blank.rawValue
    var bodyText: String = ""
    var timeZoneIdentifier: String = TimeZone.current.identifier

    var createdAt: Date = Date.distantPast
    var editedAt: Date = Date.distantPast

    @Relationship(deleteRule: .nullify) var tags: [Tag]? = []
    @Relationship(deleteRule: .nullify) var people: [Person]? = []
    @Relationship(deleteRule: .cascade, inverse: \DaySignal.dayRecord) var signals: [DaySignal]? = []

    var source: DayRecordSource {
        get { DayRecordSource(rawValue: sourceRaw) ?? .blank }
        set { sourceRaw = newValue.rawValue }
    }

    init(
        date: Date,
        source: DayRecordSource = .blank,
        bodyText: String = "",
        createdAt: Date = .now,
        timeZoneIdentifier: String = TimeZone.current.identifier
    ) {
        self.date = date
        self.sourceRaw = source.rawValue
        self.bodyText = bodyText
        self.createdAt = createdAt
        self.editedAt = createdAt
        self.timeZoneIdentifier = timeZoneIdentifier
    }

    /// True once the user has put their own words on the day, whether typed
    /// directly, composed from a guided sequence, or converted from a digest.
    var isUserWritten: Bool {
        source == .userWritten || source == .converted
    }

    /// First line of body text, used for list-row previews. A tag-only day
    /// (§5 item 4: a tag alone "counts as journaled") has no body text, so
    /// this falls back to the tag names rather than reading as blank.
    var previewLine: String {
        let firstLine = bodyText
            .split(separator: "\n", maxSplits: 1, omittingEmptySubsequences: true)
            .first
            .map(String.init) ?? ""
        guard firstLine.isEmpty else { return firstLine }

        let tagNames = (tags ?? []).map(\.name)
        return tagNames.isEmpty ? "" : tagNames.joined(separator: ", ")
    }
}
