import Foundation
import SwiftData
import AppIntents
import WidgetKit

/// The preset one-tap tokens from build spec §5 item 4. Deliberately not
/// user-extensible in this milestone — a closed set keeps the Lock Screen
/// widget's buttons enumerable ahead of time. `AppEnum` conformance lets it
/// be used directly as a widget configuration and intent parameter type.
enum PresetTag: String, CaseIterable, Identifiable, AppEnum {
    case good = "Good"
    case rough = "Rough"
    case busy = "Busy"
    case quiet = "Quiet"
    case notable = "Notable"

    var id: String { rawValue }

    static let typeDisplayRepresentation: TypeDisplayRepresentation = "Tag"

    static let caseDisplayRepresentations: [PresetTag: DisplayRepresentation] = [
        .good: "Good",
        .rough: "Rough",
        .busy: "Busy",
        .quiet: "Quiet",
        .notable: "Notable",
    ]
}

/// Applies a one-tap tag to a day, on its own constituting a valid entry
/// (§5 item 4). Shared by the in-app chip row and the Lock Screen widget's
/// `LogTagIntent` so both go through one code path.
enum TagLogger {
    @discardableResult
    static func logTag(named name: String, on date: Date, in context: ModelContext) -> DayRecord {
        let record = DayRecordRepository.record(for: date, in: context)

        var descriptor = FetchDescriptor<Tag>(predicate: #Predicate { $0.name == name })
        descriptor.fetchLimit = 1
        let tag = (try? context.fetch(descriptor).first) ?? {
            let newTag = Tag(name: name)
            context.insert(newTag)
            return newTag
        }()

        if record.tags == nil {
            record.tags = []
        }
        if record.tags?.contains(where: { $0.name == name }) != true {
            record.tags?.append(tag)
        }

        switch record.source {
        case .autoGenerated:
            record.source = .converted
        case .blank:
            record.source = .userWritten
        case .userWritten, .converted:
            break
        }
        record.editedAt = .now
        try? context.save()
        WidgetCenter.shared.reloadAllTimelines()
        return record
    }
}
