import Foundation
import SwiftData
import CoreLocation

/// Assembles and saves an auto-generated day (§9). Idempotent: re-running
/// for the same day finds the same `DayRecord` (via `DayRecordRepository`),
/// replaces only the signals it itself pulls on demand, and never
/// overwrites a day the user actually wrote or converted.
enum DigestEngine {
    /// Kinds this engine doesn't own and must never delete: visits arrive
    /// live via `LocationVisitMonitor`, shared items via the Share
    /// Extension or M8's ingestion intent, and watched-folder files via
    /// `WatchedFolderManager` — all independent write paths this engine
    /// only reads from when composing text.
    private static let pushedSignalKinds: Set<DaySignalKind> = [.visit, .sharedItem, .fileWatch, .attachment]

    /// Caller-isolated (`nonisolated(nonsending)`) so the entry view can
    /// pass its *own* main-actor context: the record on screen is then the
    /// exact object this engine rewrites, and the UI updates the moment
    /// `bodyText` changes — regenerating into a sibling context left the
    /// visible record stale. Background callers (scheduler, backfill) are
    /// unaffected; they keep running on their own executors.
    @discardableResult
    nonisolated(nonsending) static func generateDigestIfNeeded(for date: Date, in context: ModelContext) async -> DayRecord {
        let record = DayRecordRepository.record(for: date, in: context)

        // The day's bounds come from the timezone the day occurred in (the
        // record's stored zone, §10) — so provider queries cover the right
        // 24 hours even when the device has since changed zones.
        let day = DateUtilities.dayInterval(containing: date, timeZoneIdentifier: record.timeZoneIdentifier)

        guard !record.isUserWritten else { return record }

        for signal in record.signals ?? [] where !pushedSignalKinds.contains(signal.kind) {
            context.delete(signal)
        }
        record.signals?.removeAll { !pushedSignalKinds.contains($0.kind) }
        if record.signals == nil { record.signals = [] }

        var freshSignals: [DaySignal] = []
        let settings = await SettingsStore.shared

        if await settings.healthEnabled {
            freshSignals += (try? await HealthSignalProvider().collectSignals(for: day)) ?? []
        }
        if await settings.calendarEnabled {
            freshSignals += (try? await CalendarSignalProvider().collectSignals(for: day)) ?? []
        }
        if await settings.photosEnabled {
            freshSignals += (try? await PhotosSignalProvider().collectSignals(for: day)) ?? []
        }
        if await settings.mediaEnabled {
            freshSignals += (try? await MediaSignalProvider().collectSignals(for: day)) ?? []
        }
        // Visits are the primary location source, but backfilled days predate
        // installation and have none — a geotagged photo from that day is the
        // next best anchor for the weather lookup.
        if let coordinate = visitCoordinate(in: record.signals ?? []) ?? photoCoordinate(in: freshSignals),
           let weatherSignal = await WeatherSignalProvider().collectSignal(for: day, at: coordinate) {
            freshSignals.append(weatherSignal)
        }

        for signal in freshSignals {
            signal.dayRecord = record
            context.insert(signal)
        }
        record.signals?.append(contentsOf: freshSignals)

        let allSignals = record.signals ?? []
        let ruleBasedText = DigestComposer.compose(
            date: date,
            signals: allSignals,
            timeZoneIdentifier: record.timeZoneIdentifier
        )
        record.bodyText = await DigestRewriter.rewrite(ruleBasedText: ruleBasedText)
        record.source = .autoGenerated
        record.editedAt = .now
        try? context.save()

        // The reminder's whole purpose is prompting a write for a day that
        // doesn't have one yet; once this engine has composed one, that
        // prompt is stale. Only applies to today — reminders are never
        // scheduled for any other day, so there's nothing pending to cancel
        // when catch-up backfills an older day.
        if DateUtilities.startOfDay(for: date) == DateUtilities.startOfDay(for: .now) {
            NotificationManager.cancelPendingRemindersForToday()
        }

        return record
    }

    /// Walks every day strictly before today that hasn't been checked yet,
    /// generating a digest for any still without a user entry. Covers both
    /// the midnight `BGAppRefreshTask` and "the app was closed for a week"
    /// (acceptance criteria, §14) with the same code path.
    static func catchUpMissingDays(in context: ModelContext) async {
        let calendar = Calendar.current
        let today = DateUtilities.startOfDay(for: .now)
        let settings = await SettingsStore.shared
        let yesterday = calendar.date(byAdding: .day, value: -1, to: today) ?? today

        // `nil` means this has never run before — on a brand-new install
        // there's nothing to back-fill, since the app couldn't have
        // observed anything about a day before it was ever launched.
        // Falling back to `yesterday` (rather than the day before it)
        // makes the loop below process zero days on first run instead of
        // fabricating a digest for a day that predates installation.
        let lastChecked = await settings.lastDigestCheckDate ?? yesterday
        var cursor = calendar.date(byAdding: .day, value: 1, to: lastChecked) ?? yesterday

        // A generous but finite cap — this loop is O(days since last
        // launch), and nothing should ever need more than a year of catch-up.
        var daysProcessed = 0
        while cursor <= yesterday, daysProcessed < 365 {
            await generateDigestIfNeeded(for: cursor, in: context)
            cursor = calendar.date(byAdding: .day, value: 1, to: cursor) ?? yesterday
            daysProcessed += 1
        }

        await MainActor.run { settings.lastDigestCheckDate = yesterday }
    }

    /// How far back a fresh install reaches when reconstructing days the app
    /// never observed live. Health, Calendar, and Photos all answer
    /// historical queries, so a brand-new install can still tell the story
    /// of the last month. Days beyond this window stay reachable through the
    /// per-day "Generate this day" button in `EntryView`.
    static let historyBackfillDayCount = 30

    /// One-shot counterpart to `catchUpMissingDays` for days *before*
    /// installation: on a brand-new install, mines historical Health,
    /// Calendar, and Photos data to generate digests for the last
    /// `historyBackfillDayCount` days. Waits until the wizard has run (so
    /// permissions exist) and at least one signal source is enabled —
    /// otherwise every backfilled day would just read "no signals," so it
    /// stays pending until a source is turned on.
    static func backfillHistoryIfNeeded(in context: ModelContext) async {
        let settings = await SettingsStore.shared
        guard await settings.wizardCompleted, !(await settings.historyBackfillCompleted) else { return }

        let anySourceEnabled = await MainActor.run {
            settings.healthEnabled || settings.calendarEnabled
                || settings.photosEnabled || settings.mediaEnabled
        }
        guard anySourceEnabled else { return }

        let calendar = Calendar.current
        let today = DateUtilities.startOfDay(for: .now)
        for daysAgo in stride(from: historyBackfillDayCount, through: 1, by: -1) {
            guard let day = calendar.date(byAdding: .day, value: -daysAgo, to: today) else { continue }
            await generateDigestIfNeeded(for: day, in: context)
        }

        await MainActor.run { settings.historyBackfillCompleted = true }
    }

    private static func visitCoordinate(in signals: [DaySignal]) -> CLLocationCoordinate2D? {
        guard let visit = signals.first(where: { $0.kind == .visit })?.payload(as: VisitPayload.self) else {
            return nil
        }
        return CLLocationCoordinate2D(latitude: visit.latitude, longitude: visit.longitude)
    }

    private static func photoCoordinate(in signals: [DaySignal]) -> CLLocationCoordinate2D? {
        let geotagged = signals
            .filter { $0.kind == .photo }
            .compactMap { $0.payload(as: PhotoPayload.self) }
            .first { $0.latitude != nil && $0.longitude != nil }
        guard let latitude = geotagged?.latitude, let longitude = geotagged?.longitude else {
            return nil
        }
        return CLLocationCoordinate2D(latitude: latitude, longitude: longitude)
    }
}
