import Foundation
import SwiftData
import CoreLocation

/// Assembles and saves an auto-generated day (§9). Idempotent: re-running
/// for the same day finds the same `DayRecord` (via `DayRecordRepository`),
/// replaces only the signals it itself pulls on demand, and never
/// overwrites a day the user actually wrote or converted.
enum DigestEngine {
    /// Kinds this engine doesn't own and must never delete: visits arrive
    /// live via `LocationVisitMonitor`, shared items via the Share
    /// Extension or M8's ingestion intent, and watched-folder files via
    /// `WatchedFolderManager` — all independent write paths this engine
    /// only reads from when composing text.
    private static let pushedSignalKinds: Set<DaySignalKind> = [.visit, .sharedItem, .fileWatch]

    @discardableResult
    static func generateDigestIfNeeded(for date: Date, in context: ModelContext) async -> DayRecord {
        let day = DateUtilities.dayInterval(containing: date)
        let record = DayRecordRepository.record(for: date, in: context)

        guard !record.isUserWritten else { return record }

        for signal in record.signals ?? [] where !pushedSignalKinds.contains(signal.kind) {
            context.delete(signal)
        }
        record.signals?.removeAll { !pushedSignalKinds.contains($0.kind) }
        if record.signals == nil { record.signals = [] }

        var freshSignals: [DaySignal] = []
        let settings = await SettingsStore.shared

        if await settings.healthEnabled {
            freshSignals += (try? await HealthSignalProvider().collectSignals(for: day)) ?? []
        }
        if await settings.calendarEnabled {
            freshSignals += (try? await CalendarSignalProvider().collectSignals(for: day)) ?? []
        }
        if await settings.photosEnabled {
            freshSignals += (try? await PhotosSignalProvider().collectSignals(for: day)) ?? []
        }
        if let coordinate = visitCoordinate(in: record.signals ?? []),
           let weatherSignal = await WeatherSignalProvider().collectSignal(for: day, at: coordinate) {
            freshSignals.append(weatherSignal)
        }

        for signal in freshSignals {
            signal.dayRecord = record
            context.insert(signal)
        }
        record.signals?.append(contentsOf: freshSignals)

        let allSignals = record.signals ?? []
        record.bodyText = DigestComposer.compose(date: date, signals: allSignals)
        record.source = .autoGenerated
        record.editedAt = .now
        try? context.save()
        return record
    }

    /// Walks every day strictly before today that hasn't been checked yet,
    /// generating a digest for any still without a user entry. Covers both
    /// the midnight `BGAppRefreshTask` and "the app was closed for a week"
    /// (acceptance criteria, §14) with the same code path.
    static func catchUpMissingDays(in context: ModelContext) async {
        let calendar = Calendar.current
        let today = DateUtilities.startOfDay(for: .now)
        let settings = await SettingsStore.shared
        let yesterday = calendar.date(byAdding: .day, value: -1, to: today) ?? today

        let lastChecked = await settings.lastDigestCheckDate ?? calendar.date(byAdding: .day, value: -1, to: yesterday) ?? yesterday
        var cursor = calendar.date(byAdding: .day, value: 1, to: lastChecked) ?? yesterday

        // A generous but finite cap — this loop is O(days since last
        // launch), and nothing should ever need more than a year of catch-up.
        var daysProcessed = 0
        while cursor <= yesterday, daysProcessed < 365 {
            await generateDigestIfNeeded(for: cursor, in: context)
            cursor = calendar.date(byAdding: .day, value: 1, to: cursor) ?? yesterday
            daysProcessed += 1
        }

        await MainActor.run { settings.lastDigestCheckDate = yesterday }
    }

    private static func visitCoordinate(in signals: [DaySignal]) -> CLLocationCoordinate2D? {
        guard let visit = signals.first(where: { $0.kind == .visit })?.payload(as: VisitPayload.self) else {
            return nil
        }
        return CLLocationCoordinate2D(latitude: visit.latitude, longitude: visit.longitude)
    }
}
